# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect_turmor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DetectTurmor(object):
    def setupUi(self, DetectTurmor):
        DetectTurmor.setObjectName("DetectTurmor")
        DetectTurmor.resize(1354, 937)
        DetectTurmor.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(DetectTurmor)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(DetectTurmor)
        self.widget.setStyleSheet("background-color: rgb(233, 236, 255);")
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label {\n"
"    background-color: rgb(0, 170, 255);\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    border-bottom: 2px solid #3498db;\n"
"    padding: 5px;\n"
"    letter-spacing: 1px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel#label_input,\n"
"QLabel#label_output {\n"
"    font-size: 16px;\n"
"    color: #1f618d;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label_input = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.label_input.sizePolicy().hasHeightForWidth())
        self.label_input.setSizePolicy(sizePolicy)
        self.label_input.setMinimumSize(QtCore.QSize(640, 640))
        self.label_input.setMaximumSize(QtCore.QSize(640, 640))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label_input.setFont(font)
        self.label_input.setStyleSheet("QLabel {\n"
"    border: 2px solid #2980b9;\n"
"    border-radius: 10px;\n"
"    background-color: #e8f6f3;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #1f618d;\n"
"    padding: 15px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #fef9e7;\n"
"    border: 3px dashed #7dcea0;\n"
"    border-radius: 12px;\n"
"}")
        self.label_input.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input.setObjectName("label_input")
        self.horizontalLayout.addWidget(self.label_input)
        self.label_output = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.label_output.sizePolicy().hasHeightForWidth())
        self.label_output.setSizePolicy(sizePolicy)
        self.label_output.setMinimumSize(QtCore.QSize(640, 640))
        self.label_output.setMaximumSize(QtCore.QSize(640, 640))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label_output.setFont(font)
        self.label_output.setStyleSheet("QLabel {\n"
"    border: 2px solid #e67e22;\n"
"    border-radius: 10px;\n"
"    background-color: #fcf3cf;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #d35400;\n"
"    padding: 15px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"QFrame {\n"
"    background-color: #fef9e7;\n"
"    border: 3px dashed #7dcea0;\n"
"    border-radius: 12px;\n"
"}")
        self.label_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output.setObjectName("label_output")
        self.horizontalLayout.addWidget(self.label_output)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem8, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.btn_browser_2 = QtWidgets.QPushButton(self.widget)
        self.btn_browser_2.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_browser_2.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_browser_2.setFont(font)
        self.btn_browser_2.setStyleSheet("QPushButton {\n"
"    background-color: #f5b041;         /* cam nhạt */\n"
"    border: 2px solid #e67e22;         /* cam đậm */\n"
"    border-radius: 8px;\n"
"    padding: 8px 20px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eb984e;         /* khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ca6f1e;         /* khi nhấn giữ */\n"
"}")
        self.btn_browser_2.setObjectName("btn_browser_2")
        self.horizontalLayout_2.addWidget(self.btn_browser_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.btn_browser = QtWidgets.QPushButton(self.widget)
        self.btn_browser.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_browser.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_browser.setFont(font)
        self.btn_browser.setStyleSheet("QPushButton {\n"
"    background-color: #f5b041;         /* cam nhạt */\n"
"    border: 2px solid #e67e22;         /* cam đậm */\n"
"    border-radius: 8px;\n"
"    padding: 8px 20px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eb984e;         /* khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ca6f1e;         /* khi nhấn giữ */\n"
"}")
        self.btn_browser.setObjectName("btn_browser")
        self.horizontalLayout_2.addWidget(self.btn_browser)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.lineEdit_direct = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_direct.setMinimumSize(QtCore.QSize(400, 30))
        self.lineEdit_direct.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_direct.setFont(font)
        self.lineEdit_direct.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_direct.setObjectName("lineEdit_direct")
        self.horizontalLayout_2.addWidget(self.lineEdit_direct)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem13, 6, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.btn_predict = QtWidgets.QPushButton(self.widget)
        self.btn_predict.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_predict.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_predict.setFont(font)
        self.btn_predict.setStyleSheet("QPushButton {\n"
"    background-color: #f5b041;         /* cam nhạt */\n"
"    border: 2px solid #e67e22;         /* cam đậm */\n"
"    border-radius: 8px;\n"
"    padding: 8px 20px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eb984e;         /* khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ca6f1e;         /* khi nhấn giữ */\n"
"}")
        self.btn_predict.setObjectName("btn_predict")
        self.horizontalLayout_3.addWidget(self.btn_predict)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem16, 8, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.btn_save = QtWidgets.QPushButton(self.widget)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_save.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton {\n"
"    background-color: #f5b041;         /* cam nhạt */\n"
"    border: 2px solid #e67e22;         /* cam đậm */\n"
"    border-radius: 8px;\n"
"    padding: 8px 20px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eb984e;         /* khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ca6f1e;         /* khi nhấn giữ */\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 9, 0, 1, 1)
        # Thêm nút Reset Zoom
        self.horizontalLayout_reset = QtWidgets.QHBoxLayout()
        self.horizontalLayout_reset.setObjectName("horizontalLayout_reset")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_reset.addItem(spacerItem19)
        self.reset_zoom_button = QtWidgets.QPushButton(self.widget)
        self.reset_zoom_button.setMinimumSize(QtCore.QSize(100, 30))
        self.reset_zoom_button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.reset_zoom_button.setFont(font)
        self.reset_zoom_button.setStyleSheet("QPushButton {\n"
"    background-color: #f5b041;         /* cam nhạt */\n"
"    border: 2px solid #e67e22;         /* cam đậm */\n"
"    border-radius: 8px;\n"
"    padding: 8px 20px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eb984e;         /* khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ca6f1e;         /* khi nhấn giữ */\n"
"}")
        self.reset_zoom_button.setObjectName("reset_zoom_button")
        self.horizontalLayout_reset.addWidget(self.reset_zoom_button)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_reset.addItem(spacerItem20)
        self.gridLayout_2.addLayout(self.horizontalLayout_reset, 10, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem21, 11, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(DetectTurmor)
        QtCore.QMetaObject.connectSlotsByName(DetectTurmor)

    def retranslateUi(self, DetectTurmor):
        _translate = QtCore.QCoreApplication.translate
        DetectTurmor.setWindowTitle(_translate("DetectTurmor", "Form"))
        self.pushButton.setText(_translate("DetectTurmor", "More Inforation"))
        self.label.setText(_translate("DetectTurmor", "Detect Breast Cancer Image"))
        self.label_input.setText(_translate("DetectTurmor", "Input Image"))
        self.label_output.setText(_translate("DetectTurmor", "Output Image"))
        self.btn_browser_2.setText(_translate("DetectTurmor", "IMPORT DICOM"))
        self.btn_browser.setText(_translate("DetectTurmor", "BROWSER IMAGES"))
        self.lineEdit_direct.setPlaceholderText(_translate("DetectTurmor", "Image File Name Here..."))
        self.btn_predict.setText(_translate("DetectTurmor", "PREDICT"))
        self.btn_save.setText(_translate("DetectTurmor", "SAVE"))
        self.reset_zoom_button.setText(_translate("DetectTurmor", "Reset Zoom"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DetectTurmor = QtWidgets.QWidget()
    ui = Ui_DetectTurmor()
    ui.setupUi(DetectTurmor)
    DetectTurmor.show()
    sys.exit(app.exec_())